### ISSUE TITLE
[ISSUE] Error while using ChannelData class

### ISSUE THREAD

**Issue by devanshiAppperfect** [BattGenie/pycti#14]
**Error description -**
I was trying to use fetch_channel_readings method from Channel data class. But while importing this class I am getting the following error. 

![Screenshot 2024-01-03 at 3 45 08 PM](https://github.com/BattGenie/pycti/assets/111724834/732bf3cc-127a-44a6-a034-4ed9b9471dc9)

The import statement that I used is - 

![Screenshot 2024-01-03 at 3 48 47 PM](https://github.com/BattGenie/pycti/assets/111724834/d3977c21-5219-4232-8d10-7d8ebfbd9385)

Please provide with a solution.

**Comment by SyXuan** [comment]
Please use `ArbinSpoofer` directly. `ChannelData` is not a public method.
