### ISSUE TITLE
[Question] Request for Guidance: Connecting to Arbin Library without Arbin Software/Hardware

### ISSUE THREAD

**Issue by devanshiAppperfect** [BattGenie/pycti#15]
Hello there !!

I currently do not have any Arbin cyclers or related software, but I am keen on connecting to the library through spoofers to retrieve data for further analysis. In this regard, I would greatly appreciate your assistance in providing information or scheduler files that could facilitate this process.

If there are any specific procedures or resources that I need to be aware of, please guide me accordingly. I am eager to explore the capabilities of the Arbin Library and leverage the data for my projects.

Additionally, if there is a sample piece of code that accomplishes a similar connection to the library for data retrieval using spoofers, it would be of great help in understanding the integration process. I am expecting of some random data to be generated. 

Thanks.

**Comment by chintanp** [comment]
This can be done, just like to pymacnet. Closing for now. Feel free to re-open it if you have more questions,
