### ISSUE TITLE
Question about Schedule

### ISSUE THREAD

**Issue by ScubaNinja1** [BattGenie/pycti#20]
Hello, I was wondering what an example schedule file would look like, as I see you have imported them but there isn’t an example of how it is made. If you’re able to help that would be great! Thank you :)

**Comment by chintanp** [comment]
> Hello, I was wondering what an example schedule file would look like, as I see you have imported them but there isn’t an example of how it is made. If you’re able to help that would be great! Thank you :)

@ScubaNinja1 The schedule file is made in the Arbin software - MitsPro.
