### ISSUE TITLE
Add documentation for Meta Data

### ISSUE THREAD

**Issue by nickjtch** [BattGenie/pycti#6]
Can you please provide more context for Meta Data? Or at least can you please show where we can find more info about them?
That will help us contribute to the library and cover this part. Thanks!

https://github.com/BattGenie/pycti/blob/main/pyctiarbin/messages.py

**Comment by chintanp** [comment]
@nickjtch can you please specify what you mean by meta data? Maybe a link to a specific line in the file would help.

**Comment by nickjtch** [comment]
@chintanp my bad, I meant meta variables. Here's a link to the related method: https://github.com/BattGenie/pycti/blob/main/pyctiarbin/messages.py#L1086

**Comment by chintanp** [comment]
Meta variables are an Arbin construct. More details in their manual. Essentially, it is the variable that one can assign to values in a schedule. CTI docs are here: https://github.com/BattGenie/pycti/tree/main/docs and may have some info what meta variables are.

**Comment by chintanp** [comment]
@nickjtch Closing this now. Let me know if you have further questions.
